#!/usr/bin/env node
var data = require('./data');
var chart = require('./chart');

var parseParams = function(arr) {
  const nocs = arr;
  const seasons = ['winter', 'summer'];
  const medals = {'gold': 1, 'silver': 2, 'bronze': 3};

  var noc, season, medal, year;

  for (let i = 2; i < process.argv.length; i++) {
    let arg = process.argv[i];

    if (seasons.includes(arg.toLowerCase())) season = arg.toLowerCase();
    else if (medals.hasOwnProperty(arg.toLowerCase())) medal = medals[arg.toLowerCase()];
    else if (/^(18|19|20)[0-9]{2}$/.test(arg)) year = arg;
    else if (nocs.some(noc => noc.noc_name === arg.toUpperCase())) noc = arg.toUpperCase();
    else throw new Error(`Unrecognisable param: ${arg}`);
  }

  console.log(`${noc} ${season} ${medal} ${year}`);

  if (!season) throw new Error('You have to specify season param!');

  if (noc) {
    //draw amound of medals
    season = season === 'winter' ? 1 : 0;
    medal = medal || 0;
    data.getAmountOfMedals(season, noc, medal, (rows) => {
      rows = rows.map(row => [row.Year, row.Amount || 0]);
      chart.draw(rows);
    });
  }

  //draw top teams
};

data.getNOCs(parseParams);
